server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
          - Path=/service-a/**
        - id: service-b
          uri: lb://service-b
          predicates:
          - Path=/service-b/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/